version: '3.7'
networks:
    vaultnet:

services:
  vault:
    build: .
    ports:
    - "8200:8200"
    volumes:
    - "./vault.hcl:/etc/vault.d/vault.hcl"
    - "./cert:/home/vault"
    user: vault
    cap_add:
      - ALL
    depends_on:
      - db
    networks:
      - vaultnet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: goodwork
    expose:
      - "3306"      
      - "33060"
    volumes:
      - ./mysqlData:/var/lib/mysql
    networks:
      - vaultnet